# Generated by Django 3.1.1 on 2022-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='about',
            field=models.TextField(max_length=69420),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=69420),
        ),
    ]
